name: kyle-hello-world
on: push

jobs: 
  my-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out respoistory code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"